# Get all slugs to request in getStaticPaths.

# get all page slugs
query PageSlugs {
  pages {
    data {
      attributes {
        __typename
        slug
      }
    }
  }
}

# get all article-slugs
query ArticleSlugs {
  articles {
    data {
      attributes {
        __typename
        slug
      }
    }
  }
}