version: "3.9"
services:
  boilerplate-cs:
    container_name: boilerplate-cs
    build:
      context: ./cs
      dockerfile: ./Dockerfile
    image: boilerplate-cs:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: boilerplate-db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./cs/config:/opt/app/config
      - ./cs/src:/opt/app/src
      - ./cs/package.json:/opt/package.json
      - ./cs/yarn.lock:/opt/yarn.lock
      - ./.docker/transfer:/opt/app/transfer

      - .env:/opt/app/.env
      - ./cs/public:/opt/app/public
    ports:
      - "1337:1337"
    networks:
      - boilerplate
    depends_on:
      - boilerplate-db

  boilerplate-db:
    container_name: boilerplate-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.docker/data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - boilerplate

  boilerplate-adminer:
    container_name: boilerplate-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=boilerplate-db
    networks:
      - boilerplate
    depends_on:
      - boilerplate-db

  boilerplate-vs:
    container_name: boilerplate-vs
    depends_on: 
      - boilerplate-cs
      - boilerplate-db
    build: 
      context: ./vs
      dockerfile: ./Dockerfile
    image: boilerplate-vs:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    networks:
      - boilerplate
    restart: unless-stopped

networks:
  boilerplate:
    name: boilerplate
    driver: bridge
