fragment ComponentDownloadOverview on ComponentLinksDownloadOverview {
  items {
    id
    text
    media {
      data {
        attributes {
          name
          url
        }
      }
    }
  }
}
