#import '../../strapi/image/image.fragment.gql'

fragment ComponentPortfolio on ComponentGeneralPortfolio {
  portfolioItem {
    title
    description
    link {
      data {
        attributes {
          __typename
          slug
        }
      }
    }
    teaserImage {
      ...StrapiImage
    }
  }
  title
}
