#import '../../strapi/image/image.fragment.gql'

fragment ComponentGeneralTextAndImage on ComponentGeneralTextAndImage {
  __typename
  textComponent {
    text
  }
  direction
  imageComponent {
    ...StrapiImage
  }
}
