fragment ConfigHeader on Query {
  configHeader {
    data {
      attributes {
        phone
        contactPage {
          data {
            attributes {
              slug
            }
          }
        }
      }
    }
  }
}
