#import './pages/page-content.fragment.gql'
#import './articles/article-content.fragment.gql'

query ContentQuery(
  $slug: String
  $modelName: String
  $publicationState: String = "live"
) {
  findSlug(slug: $slug, modelName: $modelName, publicationState: $publicationState) {
    ...PageContent
    ...ArticleContent
  }
}
