#import '../../components/components.fragment.gql'
#import '../../strapi/seo/seo.fragment.gql'

fragment PageContent on PageEntityResponse {
  data {
    id
    attributes {
      seo {
        ...StrapiSEO
      }
      ...PageComponents
    }
  }
}
