#import '../../components/components.fragment.gql'
#import '../../strapi/seo/seo.fragment.gql'

fragment PageContent on PageEntityResponseCollection {
  data {
    id
    attributes {
      localizations {
        data {
          attributes {
            locale
            slug
          }
        }
      }
      seo {
        ...StrapiSEO
      }
      ...PageComponents
    }
  }
}
