fragment StrapiImage on ComponentInternalImage {
  image {
    data {
      attributes {
        name
        alternativeText
        caption
        url
        width
        height
        formats
      }
    }
  }
}
