#import '../../components/components.fragment.gql'
#import '../../strapi/seo/seo.fragment.gql'
#import '../../strapi/image/image.fragment.gql'

fragment ArticleContent on ArticleEntityResponse {
  data {
    id
    attributes {
      title
      publishedAt
      teaserImage {
        ...StrapiImage
      }
      seo {
        ...StrapiSEO
      }
      ...ArticleComponents
    }
  }
}
