query ArticlesQuery {
  articles {
    data {
      id
      attributes {
        title
        text {
          content
        }
      }
    }
  }
}

fragment ArticleContent on ArticleEntityResponseCollection {
  data {
    id
    attributes {
      title
      text {
        content
      }
    }
  }
}
