/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import strapiAppVersion from "@palmabit/strapi-app-version/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import locationField from "strapi-location-field-plugin/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import duplicateButton from "strapi-plugin-duplicate-button/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import oembed from "strapi-plugin-oembed/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor5: ckeditor5,
    "strapi-app-version": strapiAppVersion,
    "color-picker": colorPicker,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "location-field": locationField,
    "config-sync": configSync,
    "duplicate-button": duplicateButton,
    "multi-select": multiSelect,
    navigation: navigation,
    oembed: oembed,
  },
});
